# Bonito CTC-CRF RNN Model

[model]
package = "bonito.crf"

[labels]
labels = [ "N", "A", "C", "G", "T" ]

[input]
features = 1

[qscore]
bias = 0.0
scale = 1.0

[encoder]
stride = 5
winlen = 19
scale = 5.0
features = 768
rnn_type = "lstm"
activation = "swish"
blank_score = 2.0

single_head_layers = [ 3, 4 ]
attn_dropout = 0.1
ff_dropout = 0.1
num_attn_heads = 1

[aux_decoder]
loss_weight = 0.25
depth = 3
heads = 6
attn_dropout = 0.1
ff_dropout = 0.1
use_self_attn = false

[global_norm]
state_len = 5
