#!/bin/bash

url="https://nanoporetech.box.com/shared/static/3xwsapva4c0gjg9f3kn9ergtxo7nnueo.zip"
outfile="bonito/models/dna_r941.zip"
wget -q --show-progress --max-redirect=9 -O "$outfile" "$url"
unzip "$outfile" -d "$(dirname $outfile)"
rm -f "$outfile"
