#!/bin/bash

url="https://nanoporetech.box.com/shared/static/iatumku2snun5xfwn70wyym9cdo548mv.zip"
outfile="bonito/models/models.zip"
wget -q --show-progress --max-redirect=9 -O "$outfile" "$url"
unzip "$outfile" -d "$(dirname $outfile)"
rm -f "$outfile"
