# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Intel OpenVINO
      run: |
        sudo curl -o GPG-PUB-KEY-INTEL-OPENVINO-2020 https://apt.repos.intel.com/openvino/2020/GPG-PUB-KEY-INTEL-OPENVINO-2020
        sudo apt-key add GPG-PUB-KEY-INTEL-OPENVINO-2020
        sudo echo "deb https://apt.repos.intel.com/openvino/2020 all main" | sudo tee - a /etc/apt/sources.list.d/intel-openvino-2020.list
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends intel-openvino-dev-ubuntu18-2020.2.130

    - name: Test
      run: |
        python3 -m venv venv3
        source venv3/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        python setup.py develop
        bonito download --all

        source /opt/intel/openvino/bin/setupvars.sh
        bonito evaluate dna_r9.4.1 --device=cpu
